@baseUrl = http://localhost:8080/api/v1
@App_Vers=1.0.0.1
@email=company@gmail.com
@PhoneNumber=+250782389359
@password=1
@Auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6MiwidWlkIjoia2ViaW5lZXJpY011bmFfMTY2ODkzNTUyNSIsInBlcm1pc3Npb25WYWx1ZSI6IiIsInBlcm1pc3Npb25Kc29uIjoie1wicGVybWlzc2lvbkNvbnRyb2xsZXJcIjogXCJ2ZWZ1XCIsIFwidGVzdFwiOiBcInRydWVcIiwgXCJhcHBcIjogXCJ6ZXplXCJ9IiwidWlkQ3JlYXRvciI6IktheWlyYW5nYV8xNjY4ODc2NTE5IiwiY29tcGFueU5hbWUiOiJURUEgTFREIiwicGhvdG9VcmwiOiJub25lIiwibmFtZSI6ImtlemEiLCJlbWFpbCI6ImNvbXBhbnlAZ21haWwuY29tIiwicGFzc3dvcmQiOiJubyBQYXNzd29yZCIsImNjb2RlIjoibm9uZSIsInBob25lIjoiMDc4MjM4OTM1OSIsInBob25lTnVtYmVyIjoiKzI1MDc4MjM4OTM1OSIsImluaXRDb3VudHJ5Ijoibm9uZSIsInBsYXRmb3JtIjoiMzAwMCIsInN0YXR1cyI6ImFjdGl2ZTEiLCJzdWJzY3JpYmVyIjoiVEVBTFREIiwiY291bnRyeSI6IlVTQSIsImNyZWF0ZWRBdCI6IjIwMjItMTEtMjBUMDE6MTI6MDUtMDg6MDAiLCJ1cGRhdGVkQXQiOiIyMDIzLTA2LTE5VDEwOjI1OjE2LTA3OjAwIn0sImV4cCI6MTc2MjkwNjA3OX0.scDCjk-5LzsQrx7Tn5lqUrrHR6c2rLj9OVJ63LUJYoI
POST  {{baseUrl}}/AdminLogin
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
App-Version: {{App_Vers}}

{
"username":"test",
"password":"keza"
}
### View Sales
GET  {{baseUrl}}/checkPayment
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
App-Version: {{App_Vers}} 

{
  "pack_name": "day basic",
  "id":1,
  "input_action":"today"
 
}
### View Sales
POST  {{baseUrl}}/ViewSales
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
App-Version: {{App_Vers}} 

{
  "pack_name": "day basic",
  "id":1,
  "input_action":"today"
 
}


### Send Email
POST  {{baseUrl}}/sendEmail
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
App-Version: {{App_Vers}}

{
  "data": "https://example.com/user/12345",
  "size": 256,
  "level": "M"
}
### Generate QR code
POST  {{baseUrl}}/QrCode
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
App-Version: {{App_Vers}}

{
  "data": "https://example.com/user/12345",
  "size": 256,
  "level": "M"
}
### Upload single image
POST {{baseUrl}}/upload
App-Version: {{App_Vers}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="eric3.jpg"
Content-Type: image/jpeg

< eric.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userId"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

User profile picture
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Try to access Proteted middleware
POST  {{baseUrl}}/AdminProtected
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
App-Version: {{App_Vers}}

{
"username":"admin",
"password":"1234"

}
### Redis
GET {{baseUrl}}/Redis/
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}

{
  "email": "admin"
}
### Redis increment test realtime
POST  {{baseUrl}}/Redis/incr
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}

{
  "email": "admin"
}
### Redis Add
POST  {{baseUrl}}/Redis/add
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}

{
  "email": "admin"
}
### Redis Update
POST  {{baseUrl}}/Redis/edit
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}
{
  "email": "admin"
}
### Redis Delete
POST  {{baseUrl}}/Redis/delete
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}
{
  "email": "admin"
}
### Add Permission
GET {{baseUrl}}/LoadPermission
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}
{
  "email": "pack"
}

### Add Permission
GET {{baseUrl}}/Permission
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}
{
  "email": "zeze"
}

### Get Packages
GET {{baseUrl}}/package/
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}
{
  "role": "admin"
}

###create Package
POST {{baseUrl}}/package/add
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
App-Version: {{App_Vers}}
{
 "name": "kevine",
  "packValid": "30",
  "packCover": 2,
  "status": "active",
  "packEligible": "1",
  "packType": "Mandatory",
  "packDetail": "Access to premium parking spots",
  "price": "100",
  "commentData": "First batch",
  "created_at": "2025-10-15T10:00:00Z"


}
### Get Permission
GET {{baseUrl}}/LoadPermission
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}
{
  "email": "admin"
}
### Add Permission
GET {{baseUrl}}/Permission
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 
App-Version: {{App_Vers}}
{
  "email": "kaka"
}

### parking
GET {{baseUrl}}/payment/
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
App-Version: {{App_Vers}}
{
  "uid": "sub_001",
  "uid_user": "user_001",
  "pack_uid": "platinums_20251016131529_5641",
  "user_status": "on",
  "paid_status": "paid"


}
