@baseUrl = http://localhost:8080/api/v1
@email=company@gmail.com
@PhoneNumber=+250782389359
@password=1
@Auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6MiwidWlkIjoia2ViaW5lZXJpY011bmFfMTY2ODkzNTUyNSIsInBlcm1pc3Npb25Kc29uIjoie1wicGVybWlzc2lvbkNvbnRyb2xsZXJcIjogXCJwYWNrXCJ9IiwidWlkQ3JlYXRvciI6IktheWlyYW5nYV8xNjY4ODc2NTE5IiwiY29tcGFueU5hbWUiOiJURUEgTFREIiwicGhvdG9VcmwiOiJub25lIiwibmFtZSI6ImtlemEiLCJlbWFpbCI6ImNvbXBhbnlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMnkkMTAkRURraFVjUDFnb3o4NmVUMGVUR1F4ZVM2M2RzNkovd2k2VmpoTkIvVzJ1VFVyRjJCUW53bWUiLCJjY29kZSI6Im5vbmUiLCJwaG9uZSI6IjA3ODIzODkzNTkiLCJwaG9uZU51bWJlciI6IisyNTA3ODIzODkzNTkiLCJpbml0Q291bnRyeSI6Im5vbmUiLCJwbGF0Zm9ybSI6IjMwMDAiLCJzdGF0dXMiOiJhY3RpdmUxIiwic3Vic2NyaWJlciI6IlRFQUxURCIsImNvdW50cnkiOiJVU0EiLCJjcmVhdGVkQXQiOiIyMDIyLTExLTIwVDAxOjEyOjA1LTA4OjAwIiwidXBkYXRlZEF0IjoiMjAyMy0wNi0xOVQxMDoyNToxNi0wNzowMCJ9LCJleHAiOjE3NjE3NzI3MTd9.tPsDKJw1kdPqhORzSUEwoIdNWH6VjMbxhmZIlrsvWzA
POST  {{baseUrl}}/AdminLogin
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"username":"test",
"password":"keza"
}

### Try to access Proteted middleware
POST  {{baseUrl}}/AdminProtected
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"username":"admin",
"password":"1234"

}
### Redis
GET {{baseUrl}}/Redis/
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 

{
  "email": "admin"
}
### Redis Add
POST  {{baseUrl}}/Redis/add
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 

{
  "email": "admin"
}
### Redis Update
POST  {{baseUrl}}/Redis/edit
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 

{
  "email": "admin"
}
### Redis Delete
POST  {{baseUrl}}/Redis/delete
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 

{
  "email": "admin"
}
### Add Permission
GET {{baseUrl}}/Permission
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 

{
  "email": "pack"
}

### Get Packages
GET {{baseUrl}}/package/
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 

{
  "role": "admin"
}

###create Package
POST {{baseUrl}}/package/add
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
 "name": "kevine",
  "packValid": "30",
  "packCover": 2,
  "status": "active",
  "packEligible": "1",
  "packType": "Mandatory",
  "packDetail": "Access to premium parking spots",
  "price": "100",
  "commentData": "First batch",
  "created_at": "2025-10-15T10:00:00Z"


}
### Get Permission
GET {{baseUrl}}/LoadPermission
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 

{
  "email": "admin"
}
### Add Permission
GET {{baseUrl}}/Permission
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}} 

{
  "email": "pack"
}

### parking
GET {{baseUrl}}/payment/
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
  "uid": "sub_001",
  "uid_user": "user_001",
  "pack_uid": "platinums_20251016131529_5641",
  "user_status": "on",
  "paid_status": "paid"


}
