@baseUrl = http://localhost:8080/api/v1
@email=company@gmail.com
@PhoneNumber=+250782389359
@password=1
@Auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidWlkIjoidGhlb18xNzQ5MTQ5MDMzIiwiY2FyZHVpZCI6IiIsInVpZENyZWF0b3IiOiIiLCJzdWJzY3JpYmVyIjoiIiwicGhvdG9fdXJsIjoiIiwid2VpZ2h0IjowLCJuYW1lIjoidGhlbyIsImVtYWlsIjoib24xQGdtYWlsLmNvbV8xNzQ5MTQ5MDMyIiwicGFzc3dvcmQiOiIiLCJDY29kZSI6IiIsInBob25lIjoiIiwicGhvbmVfbnVtYmVyIjoiKzI0MzIyMjIyMjIyMiIsInBsYXRmb3JtIjoiIiwic3RhdHVzIjoiIiwiZ2VuZGVyIjoiIiwiYWdlIjoiIiwiaW5pdF9jb3VudHJ5IjoiIiwiY291bnRyeSI6IiIsIm1hcml0YWxfc3RhdHVzIjoiIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDYtMDVUMTE6NDM6NTItMDc6MDAiLCJwYWNrX3VpZCI6IiIsInBhY2tfdHlwZSI6IiIsInN0YXR1c192YWxpZCI6IiJ9LCJleHAiOjE3NTgzOTk3Nzh9.XhAuHmWR_nYMcxNRihyeg6qrrXe3sVuz8m4gzJUhXkc
POST  {{baseUrl}}/login
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"username":"test",
"password":"theo"
}
### Try to access Proteted middleware
POST  {{baseUrl}}/protected
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"username":"admin",
"password":"1234"



}
### Try to access Proteted middleware
POST  {{baseUrl}}/protectData
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"username":"admin",
"password":"123"



}
### Etags Caching
GET  {{baseUrl}}/GetTags
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}
If-None-Match: "d8e8fca2dc0f896fd7cb49"

{
"inputAction":"pepe"



}

### GET Users
GET  {{baseUrl}}/GetUsers
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"inputAction":"pepe"



}

### Create Users
POST  {{baseUrl}}/CreateUser
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"name":"keke",
"email":"vigo@gmail.com"




}




### Package ,GET
GET  {{baseUrl}}/items
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"inputAction":"pepe"



}
### Package ,POST
POST  {{baseUrl}}/Create
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"inputAction":"viewallpackage"



}